---
- name: Configure my dev machine
  hosts: localhost
  vars_files:
    - "vars/{{ ansible_distribution }}.yml"

  tasks:
  - name: Include ArchLinux-specific tasks
    import_tasks:
      file: "tasks/Archlinux.yml"
    when: ansible_distribution == 'Archlinux'

  - name: Include Ubuntu-specific tasks
    import_tasks:
      file: "tasks/Ubuntu.yml"
    when: ansible_distribution == 'Ubuntu'

  - name: Append group docker to my user
    become: true
    user:
      name: gabriel
      groups: docker
      append: yes
    tags: [user, docker]

  - name: Get .gitconfig file
    get_url:
      url: https://raw.githubusercontent.com/gabrieloliverio/dotfiles/main/.gitconfig
      dest: ~/.gitconfig
      mode: '0644'
    tags: [git]

  - name: Get .zshrc file
    get_url:
      url: https://raw.githubusercontent.com/gabrieloliverio/dotfiles/main/.zshrc
      dest: ~/.zshrc
      mode: '0644'
    tags: [zsh]

  - name: Import vim tasks
    import_tasks:
      file: "tasks/vim.yml"
    tags: [vim]

  - name: Import asdf tasks
    import_tasks:
      file: "tasks/asdf.yml"
    tags: [asdf]

  - name: Install heroku-cli
    become: true
    shell: curl https://cli-assets.heroku.com/install.sh | sh
    tags: [heroku]

  - name: Install php-cs-fixer
    become: true
    get_url:
      url: https://cs.symfony.com/download/php-cs-fixer-v3.phar
      dest: /usr/local/bin/php-cs-fixer
      mode: '0755'
    tags: [php]

  - name: Install psysh
    become: true
    get_url:
      url: https://psysh.org/psysh
      dest: /usr/local/bin/psysh
      mode: '0755'
    tags: [php]
