---
- hosts: localhost
  become: yes
  vars:
    packages:
      - firefox-developer-edition
      - composer
      - docker
      - git
      - heroku-cli
      - htop
      - php
      - php-gd
      - php-pgsql
      - php-sqlite
      - postgresql
      - python-pipenv
      - rubygems
      - transmission-qt
      - vim
      - virtualbox
      - yarn
      - watchexec
      - zsh
      
    php_extensions:
      - curl
      - pgsql
      - pdo_pgsql
      - zip
      - igbinary
  
  tasks:
  - name: full system upgrade
    pacman:
      update_cache: yes
      upgrade: yes

  - name: install packages
    package: 
      name: "{{ packages }}"
      state: latest

  - name: enable php extensions
    lineinfile:
      path: /etc/php/php.ini
      line: extension={{ item }}
    with_items: "{{ php_extensions }}"
