---
- hosts: localhost
  vars:
    packages:
      - bind
      - bitwarden
      - bitwarden-cli
      - cargo
      - composer
      - docker
      - gnu-netcat
      - htop
      - lib32-pam
      - neovim
      - npm
      - php
      - php-gd
      - php-igbinary
      - php-pgsql
      - php-sqlite
      - python-pip
      - postgresql
      - ripgrep
      - rubygems
      - tilix
      - transmission-qt
      - tree
      - vim
      - virtualbox
      - vlc
      - watchexec
      - zsh

    php_extensions:
      - curl
      - pgsql
      - pdo_pgsql
      - zip
      - igbinary

    python_packages:
      - flake8
      - mypy
  
  tasks:
  - name: full system upgrade
    become: yes
    pacman:
      update_cache: yes
      upgrade: yes
    tags: [system]

  - name: install packages
    become: yes
    package: 
      name: "{{ packages }}"
      state: latest
    tags: [packages]

  - name: install python packages
    pip:
      name: "{{ python_packages }}"
      state: latest
    tags: [python]

  - name: enable php extensions
    become: yes
    lineinfile:
      path: /etc/php/php.ini
      line: extension={{ item }}
    with_items: "{{ php_extensions }}"
    tags: [php]

  - name: install php-cs-fixer
    become: yes
    get_url:
      url: https://cs.symfony.com/download/php-cs-fixer-v3.phar
      dest: /usr/local/bin/php-cs-fixer
      mode: '0755'
    tags: [php]

  - name: create alternative npm directory
    file:
      state: directory
      path: ~/.npm-global
    tags: [node]

  - name: configure npm prefix
    shell: npm config set prefix "~/.npm-global"
    args:
      executable: /usr/bin/zsh
    tags: [node]

  - name: add ~/.npm-global to PATH
    lineinfile:
      regexp: ^PATH=~/.npm-global 
      line: PATH=~/.npm-global/bin:$PATH
      path: ~/.zshrc
    tags: [node]

  - name: install lunar vim
    shell: yes no | bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
    args:
      chdir: /tmp
      executable: /bin/bash
    tags: [vim]

  - name: copy vim config file
    get_url:
      url: https://raw.githubusercontent.com/gabrieloliverio/dotfiles/main/.vimrc
      dest: ~/.vimrc
      mode: '0644'
    tags: [vim]

  - name: copy .gitconfig file
    get_url:
      url: https://raw.githubusercontent.com/gabrieloliverio/dotfiles/main/.gitconfig
      dest: ~/.gitconfig
      mode: '0644'
    tags: [git]

  - name: source vte.sh in .zshrc for Tilix
    blockinfile:
      path: ~/.zshrc
      block: |
        if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
            source /etc/profile.d/vte.sh
        fi
    tags: [tilix]

  - name: install heroku-cli
    shell: curl https://cli-assets.heroku.com/install.sh | sh
    tags: [heroku]

