---
- hosts: localhost
  vars:
    packages:
      - bind
      - bitwarden
      - bitwarden-cli
      - firefox-developer-edition
      - composer
      - docker
      - git
      - heroku-cli
      - htop
      - php
      - php-gd
      - php-pgsql
      - php-sqlite
      - postgresql
      - python-adblock
      - python-pipenv
      - qutebrowser
      - rubygems
      - tilix
      - transmission-qt
      - tree
      - vim
      - virtualbox
      - yarn
      - watchexec
      - zsh

    aur_packages:
      - chromium-widevine # to play media in qutebrowser
      
    php_extensions:
      - curl
      - pgsql
      - pdo_pgsql
      - zip
      - igbinary

    python_packages:
      - flake8
      - mypy
  
  tasks:
  - name: full system upgrade
    become: yes
    pacman:
      update_cache: yes
      upgrade: yes
    tags: [system]

  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel
    tags: [aur, system]

  - name: allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'
    tags: [aur, system]

  - name: install packages
    become: yes
    package: 
      name: "{{ packages }}"
      state: latest
    tags: [system]

  - name: install AUR packeges
    kewlfft.aur.aur:
      name: "{{ aur_packages }}"
      state: present
      aur_only: yes
    become: yes
    become_user: aur_builder
    tags: [aur, system]

  - name: install python packages
    pip:
      name: "{{ python_packages }}"
      state: latest
    tags: [python]

  - name: enable php extensions
    become: yes
    lineinfile:
      path: /etc/php/php.ini
      line: extension={{ item }}
    with_items: "{{ php_extensions }}"
    tags: [php]
