---
- hosts: localhost
  vars:
    packages:
      - firefox-developer-edition
      - composer
      - docker
      - git
      - heroku-cli
      - htop
      - php
      - php-gd
      - php-pgsql
      - php-sqlite
      - postgresql
      - python-pipenv
      - rubygems
      - tilix
      - transmission-qt
      - tree
      - vim
      - virtualbox
      - yarn
      - watchexec
      - zsh
      
    php_extensions:
      - curl
      - pgsql
      - pdo_pgsql
      - zip
      - igbinary

    python_packages:
      - flake8
      - mypy
  
  tasks:
  - name: full system upgrade
    become: yes
    pacman:
      update_cache: yes
      upgrade: yes

  - name: install packages
    become: yes
    package: 
      name: "{{ packages }}"
      state: latest

  - name: install python packages
    pip:
      name: "{{ python_packages }}"
      state: latest
    tags: [python]

  - name: enable php extensions
    become: yes
    lineinfile:
      path: /etc/php/php.ini
      line: extension={{ item }}
    with_items: "{{ php_extensions }}"
    tags: [php]
