- name: Full system upgrade
  become: true
  apt:
    update_cache: yes
    upgrade: yes
  tags: [system]

- name: Add neovim PPA
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
  tags: [packages]

- name: Install packages
  become: true
  package: 
    name: "{{ packages }}"
    state: latest
  tags: [packages]

- name: Is oh-my-zsh installed?
  stat:
    path: $HOME/.oh-my-zsh
  register: oh_my_zsh
  tags: [zsh]

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not oh_my_zsh.stat.exists
  tags: [zsh] 

- name: Clone plugin zsh-auto-suggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags: [zsh]

- name: Download watchexec
  get_url:
    url: https://github.com/watchexec/watchexec/releases/download/cli-v1.19.0/watchexec-1.19.0-x86_64-unknown-linux-gnu.deb
    dest: /tmp
  tags: [packages, watchexec]

- name: Install watchexec
  become: true
  apt:
    deb: /tmp/watchexec-1.19.0-x86_64-unknown-linux-gnu.deb
  tags: [packages, watchexec]

- name: Install DBeaverCE downloading his .deb
  become: true
  apt:
    deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
  tags: [packages, dbeaver]

- name: Download VSCode
  become: true
  get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: /tmp/vscode.deb
  tags: [code]

- name: Install VSCode
  become: true
  apt:
    deb: /tmp/vscode.deb
  tags: [code]
